version: '3.8'

services:
  fix_engine:
    container_name: fix-engine
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./logs/benchmarks/prometheus/active:/workspace/logs/benchmarks/prometheus/active  # Share logs with node_exporter
    networks:
      - monitoring
      - FIXNET

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - /Users/nigelsaurino/docker-volumes/prometheus:/prometheus
#      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"  # <-- Explicitly set storage path
      - "--storage.tsdb.retention.time=365d"  # <-- Keep data for 1 year
    ports:
      - "9090:9090"
    networks:
      - monitoring

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    command:
      - '--collector.textfile.directory=/var/lib/node_exporter/textfile_collector'
    volumes:
      - ./logs/benchmarks/prometheus/active:/var/lib/node_exporter/textfile_collector  # Read benchmark logs
    ports:
      - "9100:9100"
    networks:
      - monitoring

  #grafana:
  #  image: grafana/grafana
  #  container_name: grafana
  #  ports:
  #    - "3000:3000"
  #  networks:
  #    - monitoring

networks:
  monitoring:
    driver: bridge
  FIXNET:
    external: true 

# volumes:
#  prometheus_data:
