version: '3.8'

services:
  fix_engine:
    container_name: fix-engine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/workspace/logs/benchmarks  # Share logs with Prometheus Node Exporter
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    volumes:
      - ./logs/benchmarks:/var/lib/node_exporter/textfile_collector  # Read benchmark logs 
    ports:
      - "9100:9100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge