version: '3.8'

services:
  fix_engine:
    container_name: fix-engine
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./logs/benchmarks/prometheus:/workspace/logs/benchmarks/prometheus  # Share logs with Prometheus Node Exporter
    networks:
      - monitoring
      - FIXNET

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./logs/benchmarks/prometheus:/var/lib/node_exporter/textfile_collector
    ports:
      - "9090:9090"
    networks:
      - monitoring

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    volumes:
      - ./logs/benchmarks/prometheus:/var/lib/node_exporter/textfile_collector  # Read benchmark logs 
    ports:
      - "9100:9100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

  FIXNET:
    driver: bridge
