global:
  scrape_interval: 10s  # Scrape benchmark results every 10 seconds

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "fix_engine_benchmarks"
    metrics_path: /metrics
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "textfile_collector"
    metrics_path: /metrics
    static_configs:
      - targets: ["node_exporter:9100"]
